name: Snake Game
on:
  schedule: # execute every 5 hours
    - cron: "0 */5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: cadusalvador
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with: 
         target_branch: output
         build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
